// 构建「离线单文件」harness：
//   1. 从 highlight.js 生成内置代码高亮主题表（离线，无需 CDN）
//   2. 用 Vite 把 harness.ts（含 @md/core / mermaid / katex / infographic / juice）
//      打成单个 ES bundle（inlineDynamicImports 内联所有动态 import）
//   3. 内联 MathJax tex-svg.js（离线公式渲染）+ JS + CSS，产出唯一的 dist/harness.html
//   4. 复制内置中文字体到 dist/fonts（运行时由 CLI 注册给 Chromium）
import { createRequire } from 'node:module'
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'vite'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, `..`)
const require = createRequire(import.meta.url)

// 1. 生成 highlight.js 主题映射表 -----------------------------------------
const stylesDir = join(dirname(require.resolve(`highlight.js/package.json`)), `styles`)
const cssFiles = readdirSync(stylesDir).filter(f => f.endsWith(`.min.css`))
const themeMap = {}
for (const f of cssFiles)
  themeMap[f.replace(/\.min\.css$/, ``)] = readFileSync(join(stylesDir, f), `utf-8`)

const genDir = join(root, `src/browser/generated`)
mkdirSync(genDir, { recursive: true })
writeFileSync(
  join(genDir, `hljs-themes.ts`),
  `// AUTO-GENERATED by scripts/build-harness.mjs — do not edit\n`
  + `export const hljsThemes: Record<string, string> = ${JSON.stringify(themeMap)}\n`,
)
console.log(`[harness] 生成 ${cssFiles.length} 个内置代码高亮主题`)

// 2. Vite 单文件打包 ------------------------------------------------------
const tmp = join(root, `dist/_harness_tmp`)
await build({
  root,
  configFile: false,
  logLevel: `warn`,
  build: {
    outDir: tmp,
    emptyOutDir: true,
    cssCodeSplit: false,
    minify: true,
    lib: {
      entry: join(root, `src/browser/harness.ts`),
      formats: [`es`],
      fileName: () => `harness.js`,
    },
    rollupOptions: { output: { inlineDynamicImports: true } },
  },
})

// 3. 组装单文件 harness.html ---------------------------------------------
const bundle = readFileSync(join(tmp, `harness.js`), `utf-8`)
let css = ``
for (const f of readdirSync(tmp)) {
  if (f.endsWith(`.css`))
    css += readFileSync(join(tmp, f), `utf-8`)
}
const mathjax = readFileSync(require.resolve(`mathjax/es5/tex-svg.js`), `utf-8`)

const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>md2wx harness</title>
${css ? `<style>${css}</style>` : ``}
<script>window.MathJax={tex:{tags:'ams'},svg:{fontCache:'none'}}</script>
<script>${mathjax}</script>
</head>
<body>
<section id="output" class="w-full"></section>
<script type="module">${bundle}</script>
</body>
</html>`

const outDir = join(root, `dist`)
mkdirSync(outDir, { recursive: true })
writeFileSync(join(outDir, `harness.html`), html)
console.log(`[harness] 写出 dist/harness.html（${(html.length / 1e6).toFixed(1)} MB，已内联 MathJax + 代码高亮）`)

// 4. 复制内置中文字体 ----------------------------------------------------
const fontSrc = join(root, `assets/fonts/NotoSansCJK-Regular.ttc`)
if (existsSync(fontSrc)) {
  mkdirSync(join(outDir, `fonts`), { recursive: true })
  copyFileSync(fontSrc, join(outDir, `fonts/NotoSansCJK-Regular.ttc`))
  console.log(`[harness] 复制内置中文字体到 dist/fonts`)
}
else {
  console.warn(`[harness] ⚠️ 未找到内置字体 ${fontSrc}`)
}

// 5. 清理临时目录 --------------------------------------------------------
rmSync(tmp, { recursive: true, force: true })
